namespace DragonWarsTrainer.Game;

/// <summary>One entry in the Dragon Wars paragraph-book cross-reference: the numbered passage the
/// game tells you to "read", and a one-line paraphrased note of what it contains.</summary>
public sealed record ParagraphEntry(int Number, string Summary)
{
    public string Label => $"#{Number}";
}

/// <summary>
/// Cross-reference index for the printed Dragon Wars paragraph book. Dragon Wars off-loads much of
/// its story into a separate booklet and, at scripted spots, prompts "read paragraph #N"; this lists
/// every numbered paragraph with a short paraphrased summary of its scene, event, or clue. The
/// passages' own prose is the game's copyrighted text and is deliberately not reproduced — these are
/// original one-line summaries condensed from that booklet, used as a lookup aid. A few numbers
/// (50, 55, 112) are absent from the source booklet. Reference only; drives no memory writes.
/// </summary>
public static class ParagraphBook
{
    public static readonly IReadOnlyList<ParagraphEntry> Paragraphs = new ParagraphEntry[]
    {
        new(1, "Chamber of crude, pornographic sculptures clearly not made by the estate's main artist."),
        new(2, "Awakened vampire lord thanks you but refuses commands until you bring the Silver Wheel, then vanishes."),
        new(3, "Well-preserved shrine to Irkalla, fierce bronze-faced dark queen of the Dilmun underworld."),
        new(4, "Purgatory's arena gate, where a guard offers you arms and a chance to win Papers of Citizenship by fighting."),
        new(5, "Purgatory's morgue reveals slaves hurl corpse sacks over the harbor wall, hinting at a possible escape route."),
        new(6, "Wilderness druid shrine to Enkidu, god of beast-men, whose druid colony was destroyed by Namtar's purge."),
        new(7, "Hiding in a corpse sack fails — guards run swords through the bags to stop escapes, leaving you helpless."),
        new(8, "Debasing yourself before Purgatory's beggars earns you a week of beatings before freedom to roam the city."),
        new(9, "Namtar's badly defaced statue in a Purgatory square, where a mad beggar spits curses at the tyrant."),
        new(10, "Hidden alley magic shop run by a friendly half-mad gnome who teaches low-level magic despite Namtar's ban."),
        new(11, "Filler passage — brief joke about Namtar's curse causing your nose to fall off, no useful clue."),
        new(12, "A guarded covered bridge — the only crossing to the land beyond — is barred by armored doors and soldiers."),
        new(13, "You are in the middle of the covered bridge, confirming it is the sole viable crossing between islands."),
        new(14, "Purgatory is a crumbling, sinking prison-city covered in anti-Namtar graffiti with no redeeming qualities."),
        new(15, "Showing a king's signet ring convinces nervous guards to let you into the city, pretending they never saw you."),
        new(16, "A camp of ragged Purgatory refugees welcomes you warmly after watching you swim across the bay."),
        new(17, "Temple of the Yellow Mud Toad in Purgatory, where the patron idol slowly sinks into the muddy floor."),
        new(18, "A slaughtered poor camp — you realize diplomacy would have served better than combat against these desperate people."),
        new(19, "Dying man Ulm shares clues about a secret Purgatory escape door and a chained Underworld goddess, then dies."),
        new(20, "Ruined plinth in the City of the Yellow Mud Toad marks where Lanac'toor's tower stood — only stone feet remain."),
        new(21, "Starving Byzanople spy post, led by a woman warrior in red and white; you remain undetected for now."),
        new(22, "Universal shrine to Dilmun's many gods — Irkalla, Nergal, Enkidu, and Refeek — tended by a tolerant priest."),
        new(23, "Murals reveal that a city square once held a captive dragon controlled by priests wielding a short magic rod."),
        new(24, "After defeating the pirates, you claim their fast raiding ship, the Prairie Madness."),
        new(25, "Phoebus's broken mechanical city greeter winds down mid-welcome but first provides a map of the city."),
        new(26, "Pristine marble-walled city with clean streets and no poverty — though something feels dangerously wrong."),
        new(27, "You stand at last before the Sword of Freedom in Freeport as the entire city watches in hushed reverence."),
        new(28, "Two Kingshomer officers enthusiastically welcome you and enlist your party into King Drake's service."),
        new(29, "Arrival in the City of the Yellow Mud Toad — a grimy, foul-smelling place of silent, shuffling citizens."),
        new(30, "Eccentric souvenir shop inside the city wall sells an obsessive range of Lanac'toor-branded merchandise."),
        new(31, "A black-sailed pirate ship spotted on the horizon is closing in and escape looks unlikely."),
        new(32, "Militia survivors recount how Kingshome used a dragon to shatter the City of the Yellow Mud Toad and petrify Lanac'toor."),
        new(33, "Byzanople's walls stand unbreached as the Kingshomer assault is bloodily repulsed by the city's defenders."),
        new(34, "Rubble-strewn killing ground before Byzanople's gates, littered with the remains of failed attackers."),
        new(35, "Lansk's fortress houses an enormous captive dragon kept by blood sacrifice as the city's last-resort defense weapon."),
        new(36, "Princess Myrilla of Byzanople confronts but then trusts you, leading you through a secret passage to her brother."),
        new(37, "Kingshomer siege engineers have tunneled under Byzanople and seek volunteers willing to sneak through and open the gates."),
        new(38, "You use magic to restore an entire frozen dwarf clan to life in their underground chamber."),
        new(39, "A quiet hidden cove with docked boats and a small shrine — possibly a place to acquire a vessel."),
        new(40, "A dungeon room enchanted to replicate a hot, swampy environment complete with mud, palms, and small reptiles."),
        new(41, "Pirate captain Long John Ugly takes your gold for dinner, then offers to ferry you to the Necropolis out of charity."),
        new(42, "Abandoned throne room holds King Drake's discarded ceremonial crown tossed carelessly behind the throne."),
        new(43, "A fog-shrouded night sail ends at a dark, moss-covered isle of ancient ruins with luminous-eyed creatures lurking in the bogs."),
        new(44, "Magic paint restores the crumbling walls of the City of the Yellow Mud Toad to full strength."),
        new(45, "A long ocean voyage east brings you at last to the gleaming modern harbor of Freeport."),
        new(46, "Journey to the wild Eastern Isles ends near a half-submerged ruined city untouched by Namtar's war."),
        new(47, "The Quag Visitors Information Bureau offers cheerful but deluded tourism for a city literally sinking into the swamp."),
        new(48, "Two scorpion-dragon-man hybrid guardians protect massive bronze doors set into a wall of rock."),
        new(49, "You fashion a makeshift hammer from boot laces and a rock, hoping it will be enough to break your chains."),
        new(51, "Freeport's clean harbor bustles with armed, industrious citizens who greet you warmly before hurrying on."),
        new(52, "Freeport's Sword of Freedom sits in a boiling harbor island — a citizen explains it protects the city but awaits a champion willing to doom it."),
        new(53, "A dungeon jester pesters you with terrible jokes; you lock him back in his cell and walk away."),
        new(54, "Restored Lanac'toor cheerfully notes his arms were put on backwards, content that it helps him scratch his back."),
        new(56, "Tarkas, exiled citizen of Tars, explains how Namtar seized control of Dilmun's defensive dragons and urges you to find a way to wrest that power away."),
        new(57, "Freeport town officials share that King Drake has not been seen in over a year and suspect Namtar's corrupting influence."),
        new(58, "Sold at slave auction, your party is put to work in Master Mog's brutal salt mines for an endless stretch."),
        new(59, "Pressed into the Kingshomer siege army, your party is billeted near Byzanople with orders to join the next assault over the wall."),
        new(60, "Mog's slave quarters — chained men sleep on cold rock, some still shackled to long-dead companions."),
        new(61, "A dying man gives you his boot laces as a parting gift, hoping they help you escape your chains."),
        new(62, "The last guard falls in the salt mines — a ladder leads up toward sunlight and freedom."),
        new(63, "Strangers share stew and a warm fire; you wake feeling genuinely reborn."),
        new(64, "Gleaming city of Lansk has clean streets, no visible weapons, no signs of war — and a faint smell of dragon."),
        new(65, "Prison guards close in, eager to beat you under the pretense of recapturing escaped prisoners."),
        new(66, "Phoebus's High Priest Mystalvision turns you over to Namtar's Stosstrupen secret police inside the Temple of the Sun."),
        new(67, "Open-air slave market in Purgatory — you contemplate the grim option of selling yourself into slavery to escape."),
        new(68, "Blind, mutilated sorcerer Carson recounts Namtar's rise, the fall of Dilmun's mages, and warns you against Mystalvision."),
        new(69, "You escape Purgatory by hiding in a corpse sack hurled over the harbor wall and swimming free in the bay."),
        new(70, "Moss-carpeted enchanted forest entrance, lit by faerie lights and charged with quiet magical atmosphere."),
        new(71, "You help the Kingshomers breach Byzanople, but commander Buck Ironhead immediately betrays you and orders you clapped in irons."),
        new(72, "A natural forest shrine where dried blood hints that the resident god responds to a small living offering."),
        new(73, "A standing-stone glade crackles with magical energy — Enkidu himself appears before you."),
        new(74, "Gamekeeper Old Jack, moved by the king's signet ring, gifts you his enchanted bow Nevermiss and charges you to defeat Namtar."),
        new(75, "A coastal shantytown of shrieking, violent madmen — a city of the insane on a desolate shore."),
        new(76, "A mad artist in the village of the lost rants incomprehensibly about earth and cows, then flees into the crowd."),
        new(77, "Self-styled King of Purgatory Clopin Trouillefou holds court over a wild mob of thieves and lunatics in a ruined square."),
        new(78, "Toxic Beach — deluded Namtar loyalists believe their bleak coastal exile is a luxury resort reward."),
        new(79, "Ghost of Zaton rises from the Underworld in a rainstorm, surrounded by beasts, and grants you knowledge to fight Namtar."),
        new(80, "Hidden chamber beneath huts holds a long-dead figure wearing Kingshome's royal colors and a signet ring."),
        new(81, "Lonely dwarf Josephina weeps that Namtar stole the icon's eyes, sealing the clanball and petrifying all her kin."),
        new(82, "Nisir, the impossibly tall Mountain of Salvation, looms above a harbor clogged with robed pilgrims."),
        new(83, "A babbling prisoner hints at a secret tunnel from the prison to Nisir, with a swamp marking the way to Namtar."),
        new(84, "Pilgrims kneel at a Universal God shrine near Nisir; you feel destiny calling you to champion freedom against Namtar."),
        new(85, "Several days' sail brings you to Nisir's pilgrim-packed harbor, the great mountain looming impossibly above."),
        new(86, "Pressed into the Kingshomer army, you are shipped to King's Island to join the long siege of Byzanople."),
        new(87, "Kingshomer campaign base camp in a mountain valley, guarded by suspicious sentries with no enemy visible nearby."),
        new(88, "Displaced old men playing dice recount how Namtar aided Kingshome's conquest and explain why no city's dragon was ever launched against him."),
        new(89, "You prevent a sacrifice, the dragon breaks free and destroys Phoebus, then flies east."),
        new(90, "General Buck Ironhead grudgingly offers you a pardon for fighting at the front, warning that Namtar will win in the end."),
        new(91, "A recently abandoned bandit camp, fire still warm — likely former adventurers who turned to crime."),
        new(92, "King Drake's gamekeeper catches you poaching a prize stag and holds you at arrow-point, waiting for your move."),
        new(93, "Nergal devours the volunteer's head in one snap after being fed, then grins in satisfaction."),
        new(94, "You identify the pool as Apsu Waters — primordial world-ocean connecting Oceana, the Underworld, and divine realms."),
        new(95, "A merciless slave boss drives you without rest or food through relentless tunnel-digging day and night."),
        new(96, "Old Jack the gamekeeper startles you in his shack, keeps his bow half-cocked, and waits for your first move."),
        new(97, "Universal God shrine atop Nisir fills you with a sense of destiny — the God needs a champion to fight for freedom."),
        new(98, "The pilgrims' path cuts into Nisir's rock high above the clouds, opening onto a plateau close to the heavens."),
        new(99, "Mog's journal reveals he used petrification potions for art, then acquired a supernatural apprentice he now fears."),
        new(100, "Ancient temple to the Magan Underworld on the plateau — older than any other structure in the area."),
        new(101, "A secret note from acolyte Berengaria unlocks your cell and directs you to a hidden escape passage and a meeting place."),
        new(102, "The drunken jailor snores with a bell tied to his wrist — waking him risks summoning guards."),
        new(103, "The master sculptor waits in his dark, mirror-free chambers and intends to make you his next stone masterpiece."),
        new(104, "A hunchback is about to sacrifice a bound prisoner to a chained dragon in a dungeon pit — you can intervene."),
        new(105, "A former beast lair, scratched with claw marks and reeking of animal — something powerful once lived here."),
        new(106, "A torture chamber holds a dying druid on the rack; you can ease his final moments but cannot save his life."),
        new(107, "Flooded ruins of Lanac'toor's tower library contain a journal fragment hinting that his lost spectacles are needed to find the College of Magic."),
        new(108, "Prince Jordan in Byzanople's underground throne room offers an alliance against Namtar, confirming King Drake's year-long disappearance."),
        new(109, "Jordan plans a surprise night raid on the Kingshomer siege camp using information you provided, and invites you to explore the city first."),
        new(110, "You and Jordan's fighters sneak from Byzanople through a secret mountain passage toward the Kingshomer camp for a night battle."),
        new(111, "Byzanople's ancestral crypt, where faint rattling chains suggest something undead stirs among the royal remains."),
        new(113, "Temple priests reward your help restoring the temple with Magic Golden Toad Boots that allow the wearer to leap great distances."),
        new(114, "Deep in the Necropolis you find the bloated, worm-riddled Nergal on a skull throne, wearing a large ornate key around his neck."),
        new(115, "After defeating Nergal's undead court he demands you also feed and serve him before he will grant any boon."),
        new(116, "A secret escape tunnel from Purgatory is real — beneath a marked rock you find fresh weapons and armor."),
        new(117, "An unusually lifelike, frightened-looking statue of a wealthy man stands in an open garden with excellent craftsmanship."),
        new(118, "A massive, heavily armed brass automaton stands silent at attention — an intimidating and dangerous piece of engineering."),
        new(119, "An entire dwarf clan has been petrified mid-activity and stands frozen throughout their underground vault."),
        new(120, "Showing the DragonGem compels the Dragon Queen to stand down and pledge to answer your next summons — if the sacrifice pleases her."),
        new(121, "Lansk's hidden undercity is a wild, raucous contrast to the orderly surface — drunken citizens and brawling soldiers fill the streets."),
        new(122, "Shrine statue of Irkalla, Queen of the Magan Underworld, whose favor is essential for surviving the Underworld."),
        new(123, "Shrine statue of Nergal, cowardly King of the Underworld, exiled to his Necropolis palace when he quarrels with Irkalla."),
        new(124, "Shrine statue of the Universal God, patron of freedom who blessed Roba of Freeport, drawing millions of pilgrims to Nisir."),
        new(125, "Shrine image of Enkidu the beastman, patron of animals and druids, whose following has faded under Namtar's rule."),
        new(126, "Lansk's captive dragon up close is old, toothless, and dulled — its fighting spirit apparently broken by age or drugs."),
        new(127, "A voice in a crystal cave reveals Namtar's full plan and names the Sword of Freedom and Underworld reconciliation as the keys to defeating him."),
        new(128, "Ashes sprinkled on dark Underworld waters summon a vortex that gradually restores an apparition to full physical life."),
        new(129, "A clandestine Dilmun Underground resistance meeting opens, all members cloaked so no faces are visible."),
        new(130, "The former imperial court of King Drake is stripped of tapestries and sculptures — clearly not occupied by a reigning king."),
        new(131, "Namtar appears as an ordinary, sleepy man who calmly explains his destiny to rule, then releases you and vanishes."),
        new(132, "Blood is painfully pumped from your volunteer to feed the Vampire Lord — a long and agonising process."),
        new(133, "A troll, amused by your participation in his customs, promises to arrange a meeting with the king under the full moon."),
        new(134, "The colossal Dragon Queen guards her sacred hive of eggs and threatens to kill you slowly as food for her brood."),
        new(135, "Namtar gloats that hiding his work in plain sight is nearly complete and his destiny is close to fulfillment."),
        new(136, "Filler passage — a philosophical aside about fools and self-delusion; no useful game clue."),
        new(137, "Irkalla is found silver-chained on the Isle of Woe by Namtar and pleads for you to bring the Silver Key to free her."),
        new(138, "The legendary Sword of Freedom rises reborn from the dark waters of the Isle of Woe."),
        new(139, "A dwarf gets an ancient airship aloft; days to the west you spot an uncharted island with a ring of standing stones."),
        new(140, "Pre-dawn trail camp reflection — hope for a future as a true citizen of Dilmun rather than a penniless outlaw."),
        new(141, "The testing voice asks you to pass a second fire-filled chamber so it can study your technique."),
        new(142, "A room with a death-gaze gargoyle fixed on the only exit — the voice challenges you to work out how to pass it."),
        new(143, "The voice praises your progress and conjures a violent warrior to test whether you can handle non-academic threats."),
        new(144, "The voice presents a room where a cable trip-wire suspends a huge granite block directly overhead — it falls silent."),
        new(145, "Utnapishtim the Faraway reveals himself as your host and asks you to show him something novel in return for his teaching."),
        new(146, "Utnapishtim congratulates you for completing his gauntlet and offers a choice among the Soul Bowl, the Laugh Staff, or the Sing Ring."),
        new(147, "A hidden valley carpeted with writhing creatures — entering Dragon Valley means near-certain death."),
    };
}
