namespace DarksypreTrainer.Game;

/// <summary>
/// One creature from the game's own <c>CR.DAT</c>. Attributes use the same six-value order as
/// the player record (STR AGI END ACC TAL PWR) and are read straight out of the creature
/// header; monsters are not bound by the player's cap of 20.
/// </summary>
public sealed record MonsterEntry(
    string Name,
    int Strength,
    int Agility,
    int Endurance,
    int Accuracy,
    int Talent,
    int Power,
    bool Ranged,
    int Tier,
    string Tactics)
{
    /// <summary>How this creature fights: at range, or hand-to-hand only.</summary>
    public string Attack => Ranged ? "Ranged" : "Melee";
}

/// <summary>
/// The 35 creatures shipped in <c>CR.DAT</c>, in file order. Generated by
/// <c>.docs/decode_game_data.py</c> — edit that script, not this file. Tactics text comes from
/// the Cheatbook walkthrough and is only filled in for the creatures it covers.
/// </summary>
internal static class MonsterBook
{
    public static IReadOnlyList<MonsterEntry> Monsters { get; } = new[]
    {
        new MonsterEntry("Slime", 8, 8, 8, 8, 8, 8, false, 1, "Poisons on contact and is immune to projectiles. Slithers under gates and does not trip weight plates. Best avoided."),
        new MonsterEntry("Giant Bee", 7, 7, 7, 7, 3, 0, false, 3, ""),
        new MonsterEntry("Giant Bat", 7, 7, 7, 7, 3, 0, false, 3, ""),
        new MonsterEntry("Wraith", 14, 12, 20, 8, 10, 0, false, 1, "Plain melee. Fight it at range with hurled weapons or fireballs."),
        new MonsterEntry("Mummy", 10, 8, 18, 8, 5, 0, false, 1, ""),
        new MonsterEntry("Gorilla", 18, 12, 12, 3, 3, 0, false, 2, ""),
        new MonsterEntry("Shadow Warrior", 12, 20, 17, 17, 5, 0, false, 2, ""),
        new MonsterEntry("Hatchling", 11, 9, 13, 6, 0, 0, false, 3, ""),
        new MonsterEntry("Scorpius", 11, 12, 14, 10, 6, 0, false, 3, ""),
        new MonsterEntry("Lizard", 13, 12, 14, 6, 3, 0, false, 3, ""),
        new MonsterEntry("Centipede", 12, 12, 14, 3, 0, 0, false, 3, ""),
        new MonsterEntry("Troll", 20, 8, 12, 4, 0, 0, false, 4, ""),
        new MonsterEntry("Gargoyle", 14, 10, 14, 16, 17, 0, false, 4, "Tough melee with good accuracy. Ranged attacks are safest."),
        new MonsterEntry("Samurai", 15, 18, 18, 12, 5, 0, false, 4, "Fast, hard-hitting melee. Keep your distance or Hold it first."),
        new MonsterEntry("Hellhound", 10, 14, 14, 9, 5, 0, false, 5, ""),
        new MonsterEntry("Cyclops", 13, 9, 12, 10, 10, 0, false, 4, ""),
        new MonsterEntry("Gelatinous Cube", 8, 8, 8, 8, 8, 8, false, 1, ""),
        new MonsterEntry("Saw Blade", 7, 10, 10, 10, 10, 0, false, 3, ""),
        new MonsterEntry("Harpy", 8, 10, 11, 14, 3, 0, true, 6, "Flies and attacks at range. Ignores weight plates."),
        new MonsterEntry("Crystal Knight", 15, 8, 20, 10, 0, 0, false, 5, ""),
        new MonsterEntry("Minotaur", 18, 13, 17, 8, 8, 0, false, 5, ""),
        new MonsterEntry("Stone Golem", 20, 7, 18, 10, 0, 0, false, 6, ""),
        new MonsterEntry("Warrior Maiden", 10, 16, 16, 15, 12, 0, false, 6, ""),
        new MonsterEntry("Evolved Slime", 14, 8, 8, 6, 6, 0, false, 10, ""),
        new MonsterEntry("Manta Ray", 9, 10, 9, 9, 7, 0, false, 7, "Flies, so it ignores weight plates. Use hurled weapons or fireballs."),
        new MonsterEntry("Jester", 8, 12, 12, 15, 10, 10, true, 6, "The only walker that also throws fireballs and gas. Hold or Freeze it, or burn it down fast."),
        new MonsterEntry("Muskateer", 12, 16, 13, 4, 3, 0, false, 8, ""),
        new MonsterEntry("Crustacean", 6, 2, 0, 0, 6, 6, false, 6, "Plain melee. Fight it at range with hurled weapons or fireballs."),
        new MonsterEntry("Pheonix", 10, 21, 13, 13, 10, 10, true, 6, "Flies and attacks at range. Very fast; Freeze buys you room."),
        new MonsterEntry("Djinn", 8, 8, 10, 12, 16, 0, true, 6, "Floats and throws poison gas. Close to melee range or Hold it."),
        new MonsterEntry("Gryphon", 12, 14, 16, 13, 15, 0, true, 6, "Flies and attacks at range. Close in or Hold it."),
        new MonsterEntry("Creeper", 6, 10, 12, 10, 5, 0, false, 1, "Poisons on contact and is immune to projectiles. Hit once, back off, repeat."),
        new MonsterEntry("Electric Ball", 7, 10, 17, 14, 14, 0, true, 1, "Floats and fires at range. Close to melee range or Hold it."),
        new MonsterEntry("Beholder", 11, 14, 13, 14, 15, 0, true, 1, "Floats and fires at range. Close to melee to suppress its shots, or Hold it."),
        new MonsterEntry("Spartan Warrior", 25, 25, 25, 6, 7, 0, false, 10, "End-game melee with 25s across the board. Freeze first, or avoid."),
    };

    /// <summary>Creatures that attack at range (fireballs, bolts or gas).</summary>
    public static IReadOnlyList<MonsterEntry> Ranged => Monsters.Where(m => m.Ranged).ToList();
}
