<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <AssemblyName>FormatCheck</AssemblyName>
    <RootNamespace>TheQuestTrainer.FormatCheck</RootNamespace>
    <Platforms>AnyCPU;x64</Platforms>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TheQuestTrainer\TheQuestTrainer.csproj" />
  </ItemGroup>

</Project>
