<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <AssemblyName>FormatCheck</AssemblyName>
    <RootNamespace>Space1889Trainer.FormatCheck</RootNamespace>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="GameTrainers.Common.Documents" />
    <Using Include="GameTrainers.Common.Memory" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Space1889Trainer\Space1889Trainer.csproj" />
  </ItemGroup>

</Project>
