<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <RootNamespace>LegendOfFaerghailTrainer.FormatCheck</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LegendOfFaerghailTrainer\LegendOfFaerghailTrainer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="GameTrainers.Common.Memory" />
  </ItemGroup>

</Project>
