<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <AssemblyName>KnightsOfLegendTrainer</AssemblyName>
    <RootNamespace>KnightsOfLegendTrainer</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\GameTrainers.Common\GameTrainers.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FormatCheck" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="GameTrainers.Common.Documents" />
    <Using Include="GameTrainers.Common.Memory" />
    <Using Include="GameTrainers.Common.Mvvm" />
    <Using Include="System.Collections.ObjectModel" />
    <Using Include="KnightsOfLegendTrainer.ViewModels" />
    <Using Include="KnightsOfLegendTrainer.Game" />
  </ItemGroup>

</Project>
