namespace LegendOfFaerghailTrainer.Game;

/// <summary>One row of the game's item table: id, display name, and shop price.</summary>
public readonly record struct ItemInfo(int Id, string Name, long Price);

/// <summary>
/// The complete item table, read out of <c>LOF.EXE</c> at file offset 0x42CCC: 186 records of 32
/// bytes each, the first 16 being a NUL-padded name and the word at +0x14 the shop price. Id 0 is
/// a blank sentinel the game uses for an empty inventory slot.
///
/// The base offset was fixed by the running game rather than guessed: the shipped Connar carries
/// item ids 27, 34 and 13, and his sheet lists "Leather armour", "Small shield" and "Short sword" —
/// which lines up only if the table starts one record before the first named entry ("Club" is id 1).
/// The remaining 12 bytes of each record are unidentified; +0x12 is a plausible weight for armour
/// and a plausible damage figure for weapons, but the two readings disagree on the same field, so
/// neither is claimed here.
/// </summary>
public static class ItemBook
{
    public static readonly ItemInfo[] All =
    {
        new(0, "(none)", 0),
        new(1, "Club", 100),
        new(2, "War scythe", 70),
        new(3, "Hand axe", 50),
        new(4, "Footman's flail", 80),
        new(5, "Footman's mace", 80),
        new(6, "Trident", 40),
        new(7, "Quarterstaff", 50),
        new(8, "Warhammer", 60),
        new(9, "Morningstar", 60),
        new(10, "Battle axe", 80),
        new(11, "Battle flail", 110),
        new(12, "Rapier", 30),
        new(13, "Short sword", 50),
        new(14, "Broadsword", 80),
        new(15, "Bardiche", 120),
        new(16, "Bastard sword", 120),
        new(17, "Two handed swrd", 456),
        new(18, "Sling", 5),
        new(19, "Bullets", 2),
        new(20, "Short bow", 60),
        new(21, "Short arrows", 10),
        new(22, "Long bow", 120),
        new(23, "Long arrows", 4),
        new(24, "Crossbow", 100),
        new(25, "Bolts", 10),
        new(26, "Robe", 80),
        new(27, "Leather armour", 150),
        new(28, "Studded leather", 200),
        new(29, "Scale mail", 400),
        new(30, "Chain mail", 300),
        new(31, "Ring mail", 350),
        new(32, "Plate mail", 450),
        new(33, "Full plate", 650),
        new(34, "Small shield", 50),
        new(35, "Large shield", 90),
        new(36, "Tinderbox", 4),
        new(37, "Torch", 40),
        new(38, "Flask of oil", 10),
        new(39, "Lantern", 8),
        new(40, "Spellbook", 60),
        new(41, "Holy symbol", 10),
        new(42, "Thieves' picks", 2),
        new(43, "Anvil", 240),
        new(44, "Sledge-hammer", 80),
        new(45, "Barbarian axe", 476),
        new(46, "Holy water", 5),
        new(47, "Healing potion", 4),
        new(48, "Poison I", 6),
        new(49, "Antidote I", 25),
        new(50, "Shield ring", 1),
        new(51, "Elven chain", 150),
        new(52, "Healing II", 6),
        new(53, "Poison II", 6),
        new(54, "Antidote II", 25),
        new(55, "Protecting ring", 1),
        new(56, "Strength potion", 6),
        new(57, "Heroes' drink", 6),
        new(58, "Potion of Kybol", 8),
        new(59, "Potion of haste", 10),
        new(60, "Enchant weapon", 3),
        new(61, "Friendship ring", 2),
        new(62, "Enchant armour", 3),
        new(63, "Ring of Kybol", 2),
        new(64, "Striking staff", 5),
        new(65, "Polymorph wand", 5),
        new(66, "Scroll of power", 3),
        new(67, "Healing III", 6),
        new(68, "Ring of power", 2),
        new(69, "Healers' staff", 5),
        new(70, "Rod of fear", 5),
        new(71, "Gain level", 8),
        new(72, "Drain level", 6),
        new(73, "Lightbringer", 65),
        new(74, "Staff of sun", 5),
        new(75, "Blade of power", 65),
        new(76, "Blizz. sceptre", 5),
        new(77, "Catchpoles hilt", 65),
        new(78, "Staff of age", 5),
        new(79, "Staff of death", 5),
        new(80, "Ring of shelter", 1),
        new(81, "Antimagic ring", 2),
        new(82, "Staff of life", 5),
        new(83, "Inquisitor", 65),
        new(84, "Stonesword", 250),
        new(85, "Crystal sword", 120),
        new(86, "Gods' hammer", 100),
        new(87, "Elven bow", 80),
        new(88, "David's sling", 1),
        new(89, "Crystal ball", 20),
        new(90, "Elven cloak", 40),
        new(91, "Drum of fear", 40),
        new(92, "1st Bookhalf", 12),
        new(93, "2nd Bookhalf", 12),
        new(94, "The Emerald", 5),
        new(95, "The Corona", 2),
        new(96, "The Keystaff", 15),
        new(97, "Papyrus scroll", 3),
        new(98, "Mithril ball", 6),
        new(99, "Death mask", 12),
        new(100, "Sarcophagus", 3000),
        new(101, "Pergament", 3),
        new(102, "Scroll", 3),
        new(103, "Shaolin's Staff", 40),
        new(104, "Dragon chain", 300),
        new(105, "Dragon plate", 400),
        new(106, "Dragon leather", 80),
        new(107, "Book of herbs", 30),
        new(108, "Book of stars", 35),
        new(109, "Crafts", 30),
        new(110, "Lord of rinse", 70),
        new(111, "Orthografy", 30),
        new(112, "Spade", 75),
        new(113, "Gunpowder", 10),
        new(114, "Leather pouch", 0),
        new(115, "Small shield+", 40),
        new(116, "Broadsword+2", 80),
        new(117, "Rope", 5),
        new(118, "Large shield+", 105),
        new(119, "Magic protect.", 3),
        new(120, "The Amulet", 0),
        new(121, "Broadsword+", 80),
        new(122, "Broadsword+2", 80),
        new(123, "Long arrows+2", 5),
        new(124, "Talisman", 5),
        new(125, "Crystal wedge", 5),
        new(126, "Protection", 3),
        new(127, "Gnokem Whisky", 6),
        new(128, "Quarterstaff+", 40),
        new(129, "Staff of light", 5),
        new(130, "Document", 3),
        new(131, "Full plate", 600),
        new(132, "Bucket of sand", 0),
        new(133, "Golden key", 4),
        new(134, "12 Rations", 60),
        new(135, "Count Dracula", 70),
        new(136, "The capital", 70),
        new(137, "Golden casket", 200),
        new(138, "Chest", 350),
        new(139, "Nugget", 10),
        new(140, "Big Nugget", 70),
        new(141, "Lump of Adamit", 55),
        new(142, "Blue map", 3),
        new(143, "Small map", 3),
        new(144, "Strange map", 3),
        new(145, "Map scrap", 3),
        new(146, "Old map", 3),
        new(147, "Boring map", 3),
        new(148, "Lump of Adamit", 30),
        new(149, "Stonekey", 4),
        new(150, "Mirrorshield", 75),
        new(151, "Steelkey", 4),
        new(152, "Copperkey", 4),
        new(153, "Coal sack", 150),
        new(154, "Iron key", 4),
        new(155, "Ring key", 4),
        new(156, "Ruby key", 4),
        new(157, "Sacred dagger", 20),
        new(158, "Key of fire", 4),
        new(159, "Key of water", 4),
        new(160, "Key of air", 4),
        new(161, "Key of earth", 4),
        new(162, "Key of light", 4),
        new(163, "True scroll", 3),
        new(164, "Glassy key", 4),
        new(165, "Bone key", 4),
        new(166, "Dry clay", 4),
        new(167, "Some water", 4),
        new(168, "Lump of clay", 8),
        new(169, "Dry clay key", 4),
        new(170, "Wet clay key", 4),
        new(171, "Golden sword", 80),
        new(172, "Golden figurine", 5),
        new(173, "Diadem", 5),
        new(174, "Crank-handle", 5),
        new(175, "Seal ring", 2),
        new(176, "Bird's nest", 1),
        new(177, "Ladle", 3),
        new(178, "Caught vampire", 602),
        new(179, "Tin key", 2),
        new(180, "Water jug", 15),
        new(181, "Bone", 1),
        new(182, "Door key", 1),
        new(183, "Ugly map", 3),
        new(184, "The Ring", 7),
        new(185, "The Staff", 22),
    };

    public static int Count => All.Length;

    public static string NameOf(int id) =>
        id >= 0 && id < All.Length ? All[id].Name : $"Item {id}";

    public static long PriceOf(int id) =>
        id >= 0 && id < All.Length ? All[id].Price : 0;
}
