namespace LegendOfFaerghailTrainer.Game;

/// <summary>One row of the game's spell table: id and display name.</summary>
public readonly record struct SpellInfo(int Id, string Name);

/// <summary>
/// The complete spell table, read out of <c>LOF.EXE</c> at file offset 0x4440C: 36-byte records
/// whose first 22 bytes are a NUL-padded name. Id 0 is a blank sentinel for an empty spell slot.
/// Ids 1..141 are real; the entries past 141 are unrelated text the table runs into.
///
/// The base was fixed the same way as the item table: a live Magician's record held spell ids 1 and
/// 2 while his sheet listed "Burning hands" and "Light", which only matches if the first named
/// entry is id 1. Ids 128..141 kept their German names in this English build ("Rang erniedrigen" =
/// reduce rank, "Drachenatem" = dragon breath); they are monster and event effects rather than
/// spells a character learns, and are listed here exactly as the executable spells them.
/// </summary>
public static class SpellBook
{
    public static readonly SpellInfo[] All =
    {
        new(0, "(none)"),
        new(1, "Burning hands"),
        new(2, "Light"),
        new(3, "Magic arrow"),
        new(4, "Shield I"),
        new(5, "Word of sleep"),
        new(6, "Schocking grasp"),
        new(7, "Permanent light"),
        new(8, "Fireworks"),
        new(9, "Magic net"),
        new(10, "Word of weakening"),
        new(11, "Lightning bolt"),
        new(12, "Invisibility"),
        new(13, "Fireball"),
        new(14, "Ray of fire"),
        new(15, "Fading"),
        new(16, "Haste"),
        new(17, "Paralyze"),
        new(18, "Shield II"),
        new(19, "Slow"),
        new(20, "Blizzard"),
        new(21, "Flame shield"),
        new(22, "Word of fear"),
        new(23, "Word of altering"),
        new(24, "Word of confusion"),
        new(25, "Summon elemental"),
        new(26, "Icy ray"),
        new(27, "Petrify"),
        new(28, "Death cloud"),
        new(29, "Disintegrate"),
        new(30, "Word of death"),
        new(31, "Mind shock"),
        new(32, "Magic shield"),
        new(33, "Acid ray I"),
        new(34, "Colour rays"),
        new(35, "Haste"),
        new(36, "Magic lantern"),
        new(37, "Mud"),
        new(38, "Phantom armour"),
        new(39, "Magic map"),
        new(40, "Open locks"),
        new(41, "Blind"),
        new(42, "Smoke cloud"),
        new(43, "Disarm traps"),
        new(44, "Farsightedness"),
        new(45, "Lightning bolt"),
        new(46, "Invisibility"),
        new(47, "Acid ray II"),
        new(48, "Entanglement"),
        new(49, "Polymorph"),
        new(50, "Surprise"),
        new(51, "Phantom shield"),
        new(52, "Flame fist"),
        new(53, "Heart attack"),
        new(54, "Slow down"),
        new(55, "Rainbow hues"),
        new(56, "Phantom"),
        new(57, "Sunlight"),
        new(58, "Phantom prison"),
        new(59, "Glow"),
        new(60, "Enchant weapon"),
        new(61, "Animal friendship"),
        new(62, "Firetrap"),
        new(63, "Healing I"),
        new(64, "Friendship"),
        new(65, "Wooden skin"),
        new(66, "Disarm traps"),
        new(67, "Flicker"),
        new(68, "Summon insects"),
        new(69, "Thunderbolt I"),
        new(70, "Thunderbolt II"),
        new(71, "Summon Woodkeeper"),
        new(72, "Hailstorm"),
        new(73, "Cyclone"),
        new(74, "Healing II"),
        new(75, "Summon elemental"),
        new(76, "Fiery aerolite"),
        new(77, "Imbecility"),
        new(78, "Sand storm"),
        new(79, "Death ray"),
        new(80, "Healing I"),
        new(81, "Light"),
        new(82, "Fear evil"),
        new(83, "Blessing"),
        new(84, "Fear undead"),
        new(85, "Mental hammer"),
        new(86, "Singing"),
        new(87, "Bind persons"),
        new(88, "Silence"),
        new(89, "Relieve poison"),
        new(90, "Prayer"),
        new(91, "Remove curse"),
        new(92, "Healing II"),
        new(93, "Flame punch"),
        new(94, "Insect swarm"),
        new(95, "Annihilate evil"),
        new(96, "Blade wall"),
        new(97, "Summon warrior"),
        new(98, "Earthquake"),
        new(99, "Protection"),
        new(100, "Cure light wounds"),
        new(101, "Singing"),
        new(102, "Shield"),
        new(103, "Stun"),
        new(104, "Cure serious wounds"),
        new(105, "Light"),
        new(106, "Blessing"),
        new(107, "Cure blindness"),
        new(108, "Healing III"),
        new(109, "Cure poison"),
        new(110, "Refresh"),
        new(111, "Cure illness"),
        new(112, "Shelter"),
        new(113, "Threaten"),
        new(114, "Dispell undead"),
        new(115, "Remove curse"),
        new(116, "Restoration"),
        new(117, "Magic cage"),
        new(118, "Disrupt"),
        new(119, "Dismay"),
        new(120, "Enchant weapon"),
        new(121, "Enchant armour"),
        new(122, "Crystal ball"),
        new(123, "Quake"),
        new(124, "Paralyze"),
        new(125, "Vibration"),
        new(126, "Iron sparks"),
        new(127, "Titan's fist"),
        new(128, "Rang erniedrigen"),
        new(129, "Regeneration I"),
        new(130, "Regeneration II"),
        new(131, "Drachenatem I"),
        new(132, "Rang erhöhen"),
        new(133, "Altern"),
        new(134, "Lähmen"),
        new(135, "Wiedererwecken"),
        new(136, "Sofortiger Tod"),
        new(137, "Vernichten"),
        new(138, "Berzerker"),
        new(139, "Flammenfaust"),
        new(140, "Attribut erhöhen"),
        new(141, "Drachenatem II"),
    };

    public static int Count => All.Length;

    public static string NameOf(int id) =>
        id >= 0 && id < All.Length ? All[id].Name : $"Spell {id}";
}
